//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterpConsoleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class LabLookup
    {
        public int ID { get; set; }
        public string FacilityName { get; set; }
        public string LabName { get; set; }
        public string LabCode { get; set; }
        public string ResultName { get; set; }
        public string ResultCode { get; set; }
        public string ResultValue { get; set; }
        public Nullable<bool> IsPositive { get; set; }
        public string CommonLabName { get; set; }
        public string CommonResultName { get; set; }
        public Nullable<bool> CanSkip { get; set; }
    }
}
